all:
	gcc -std=c++11 Camera_Grab.cpp -o activate_onboard_camera -L/usr/lib -lstdc++ -lopencv_core -lopencv_highgui -lopencv_videoio -lopencv_imgproc -lopencv_imgcodecs

clean:
	rm -rf activate_onboard_camera
